name: pgscen
channels:
  - conda-forge
dependencies:
  - python=3.8
  - r-essentials=4.2
  - r-envstats
  - r-robustbase
  - r-quantreg
  - r-mvtnorm
  - r-quadprog
  - r-scatterplot3d
  - r-tseries
  - r-plot3d
  - libgfortran5
  - pandas==1.5.3
  - rpy2==3.5.11

