name: powscen
channels:
  - conda-forge 
dependencies:
  - python=3.8
  - r-essentials=4.0
  - r-base=4.0
  - rpy2
  - numpy
  - scipy
  - pandas
  - statsmodels
  - matplotlib
  - jupyterlab
  - openpyxl
  - h5py
  - pip
  - pip:
    - astral
