name: pgscen
channels:
  - conda-forge
dependencies:
  - python=3.8
  - numpy
  - scipy
  - pandas
  - dill
  - matplotlib
  - statsmodels
  - cffi
  - jupyterlab
  - seaborn
  - openpyxl
  - rpy2
  - geopandas
  - ipywidgets
  - r-essentials=4.0
  - r-glasso
  - r-qgraph
  - r-envstats
  - r-robustbase
  - r-rgl
  - r-quantreg
  - r-mvtnorm
  - r-quadprog
  - r-scatterplot3d
  - r-tseries
  - r-plot3d
  - pip:
    - astral
