name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-18.04, macos-11, macos-10.15]

    steps:
      - uses: actions/checkout@v2

      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          environment-file: environment.yml
          auto-activate-base: false

      - name: test-run
        shell: bash -l {0}
        run: |
          cd $GITHUB_WORKSPACE
          pip install -e .
          sh test/test_run.sh
          pip install .
          sh test/test_run.sh
          echo tests finished successfully!

